/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LoanService } from "../loan.service";
import { LoanCreateInput } from "./LoanCreateInput";
import { Loan } from "./Loan";
import { LoanFindManyArgs } from "./LoanFindManyArgs";
import { LoanWhereUniqueInput } from "./LoanWhereUniqueInput";
import { LoanUpdateInput } from "./LoanUpdateInput";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";

export class LoanControllerBase {
  constructor(protected readonly service: LoanService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Loan })
  async createLoan(@common.Body() data: LoanCreateInput): Promise<Loan> {
    return await this.service.createLoan({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,
        id: true,
        installmentAmount: true,
        installmentFrequency: true,
        issuedDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Loan] })
  @ApiNestedQuery(LoanFindManyArgs)
  async loans(@common.Req() request: Request): Promise<Loan[]> {
    const args = plainToClass(LoanFindManyArgs, request.query);
    return this.service.loans({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,
        id: true,
        installmentAmount: true,
        installmentFrequency: true,
        issuedDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Loan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async loan(
    @common.Param() params: LoanWhereUniqueInput
  ): Promise<Loan | null> {
    const result = await this.service.loan({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,
        id: true,
        installmentAmount: true,
        installmentFrequency: true,
        issuedDate: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Loan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLoan(
    @common.Param() params: LoanWhereUniqueInput,
    @common.Body() data: LoanUpdateInput
  ): Promise<Loan | null> {
    try {
      return await this.service.updateLoan({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,
          dueDate: true,
          id: true,
          installmentAmount: true,
          installmentFrequency: true,
          issuedDate: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Loan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLoan(
    @common.Param() params: LoanWhereUniqueInput
  ): Promise<Loan | null> {
    try {
      return await this.service.deleteLoan({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          dueDate: true,
          id: true,
          installmentAmount: true,
          installmentFrequency: true,
          issuedDate: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: LoanWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        id: true,

        loan: {
          select: {
            id: true,
          },
        },

        paymentDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  async connectPayments(
    @common.Param() params: LoanWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updateLoan({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  async updatePayments(
    @common.Param() params: LoanWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updateLoan({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  async disconnectPayments(
    @common.Param() params: LoanWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updateLoan({
      where: params,
      data,
      select: { id: true },
    });
  }
}
